version: '3.1'

services:

  #mongo:
    #image: mongo:latest
    #container_name: mongo
    #ports:
    #  - 27017:27017
    #networks:
    #  - backend

  be:
    build:
      context: ./be
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - DATABASE_URL=mongodb+srv://unnatiaggarwal13:H2xSOwdoPcZAsKO8@cluster0.3sfln4d.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - DATABASE_TEST_URL=mongodb+srv://unnatiaggarwal13:H2xSOwdoPcZAsKO8@cluster0.3sfln4d.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    networks:
      - backend

  fe:
    stdin_open: true
    build:
      context: ./fe
      dockerfile: Dockerfile
    ports:
      - 3007:80
    environment:
      - REACT_APP_BE_NETWORK=backend
      - REACT_APP_BE_PORT=5000
      - REACT_APP_API_SERVICE_URL=${REACT_APP_API_SERVICE_URL}
    depends_on:
      - be
    networks:
      - frontend
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
